services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sub:/srv/${SUB_PATH}
      - caddy-data:/data

  minio:
    image: quay.io/minio/minio:latest
    command: server /tmp --console-address ":9001"
    restart: always
    network_mode: host
    env_file: .env

volumes:
  caddy-data:
